const codinomes = [
    "Sombra Negra",
    "Lâmina de Prata",
    "Estrela da Manhã",
    "Dragão de Fogo",
    "Olho de Corvo",
    "Estrela Cadente",
    "Martelo Trovejante",
    "Manto das Sombras",
    "Coração de Leão",
    "Lobo Solitário",
    "Espada da Aurora",
    "Cavaleiro da Lua",
    "Vento Veloz",
    "Lâmina Flamejante",
    "Corvo Noturno",
    "Mão de Ferro",
    "Lírio da Noite",
    "Sussurros da Bruma",
    "Falcão Dourado",
    "Pérola da Tempestade",
    "Lâmina de Gelo",
    "Sussurros da Serpente",
    "Dragão das Sombras",
    "Olho de Falcão",
    "Corça Veloz",
    "Mão de Prata",
    "Espectro da Noite",
    "Lobo Negro",
    "Manto da Alvorada",
    "Espada Reluzente",
    "Fênix Dourada",
    "Mão de Ferro",
    "Lírio Noturno",
    "Estrela Guia",
    "Vento Sussurrante",
    "Lâmina Relampejante",
    "Cavaleiro da Serpente",
    "Estrela do Crepúsculo",
    "Sussurros da Lua",
    "Dragão de Gelo",
    "Olho da Coruja",
    "Corça Ágil",
    "Martelo de Ferro",
    "Lobo da Noite",
    "Manto Estelar",
    "Espada do Sol",
    "Fênix Flamejante",
    "Mão de Marfim",
    "Lírio da Bruma",
    "Espectro das Sombras",
    "Lobo da Alvorada",
    "Sussurros da Estrela",
    "Dragão da Tempestade",
    "Olho da Serpente",
    "Corvo das Sombras",
    "Martelo Trovejante",
    "Estrela Noturna",
    "Vento Veloz",
    "Lâmina Flamejante",
    "Corça da Lua",
    "Mão de Ferro",
    "Lírio de Gelo",
    "Sussurros da Bruma",
    "Falcão Dourado",
    "Pérola da Tempestade",
    "Lâmina de Gelo",
    "Sussurros da Serpente",
    "Dragão da Lua",
];

module.exports = codinomes;