const itens = [
    { nome: 'Barraca (2 pessoas)', preco: 5, peso: 100 },
    { nome: 'Baú (pequeno)', preco: 3, peso: 5 },
    { nome: 'Baú (médio)', preco: 10, peso: 100 },
    { nome: 'Baú (grande)', preco: 20, peso: 400 },
    { nome: 'Casaco de pele', preco: 5, peso: 20 },
    { nome: 'Corrente (10’)', preco: 25, peso: 40 },
    { nome: 'Escada (10’)', preco: 5, peso: 10 },
    { nome: 'Grimório (100 pg)', preco: 25, peso: 100 },
    { nome: 'Instrumento musical', preco: 10, peso: 10 },
    { nome: 'Pá', preco: 2, peso: 5 },
    { nome: 'Pé de cabra', preco: 3, peso: 5 },
    { nome: 'Picareta', preco: 3, peso: 10 },
    { nome: 'Polia', preco: 5, peso: 20 },
    { nome: 'Rede', preco: 5, peso: 20 },
    { nome: 'Serra', preco: 1, peso: 5 },
    { nome: 'Símbolo Sagrado', preco: 25, peso: 5 },
    { nome: 'Vara de exploração', preco: 1, peso: 20 },
    { nome: 'Vara de pescaria', preco: 5, peso: 5 },
    { nome: 'Água benta (frasco)', preco: 25 },
    { nome: 'Agulha (1’’)', preco: 1 },
    { nome: 'Alicate', preco: 2 },
    { nome: 'Algema (par)', preco: 15 },
    { nome: 'Ampulheta (pequena, 10 min)', preco: 10 },
    { nome: 'Ampulheta (grande, 60 min)', preco: 20 },
    { nome: 'Apito', preco: 3 },
    { nome: 'Barbante (rolo de 100’)', preco: 1 },
    { nome: 'Berrante', preco: 5 },
    { nome: 'Bolas de gude (6)', preco: 1 },
    { nome: 'Bolsa de cinto', preco: 3 },
    { nome: 'Carvão (saco)', preco: 1 },
    { nome: 'Cera de abelha', preco: 1 },
    { nome: 'Cobertor', preco: 1 },
    { nome: 'Corda (50’)', preco: 1 },
    { nome: 'Corda especial (50’)', preco: 10 },
    { nome: 'Dados (2 unidades)', preco: 1 },
    { nome: 'Espelho (pequeno)', preco: 5 },
    { nome: 'Estacas de madeira (3)', preco: 1 },
    { nome: 'Estrepes (bolsa com 10)', preco: 1 },
    { nome: 'Frasco de vidro (1 qt)', preco: 1 },
    { nome: 'Gancho', preco: 25 },
    { nome: 'Gazua', preco: 20 },
    { nome: 'Giz', preco: 1 },
    { nome: 'Lampião', preco: 10 },
    { nome: 'Lupa', preco: 10 },
    { nome: 'Mochila', preco: 5 },
    { nome: 'Óleo (frasco)', preco: 2 },
    { nome: 'Odre', preco: 1 },
    { nome: 'Panela de ferro', preco: 1 },
    { nome: 'Papiro (uma unidade)', preco: 5 },
    { nome: 'Pinos de ferro (12)', preco: 1 },
    { nome: 'Pederneira', preco: 2 },
    { nome: 'Porta mapas', preco: 1 },
    { nome: 'Ração, 7 dias (simples)', preco: 3 },
    { nome: 'Ração, 7 dias (especial)', preco: 15 },
    { nome: 'Roupa comum', preco: 1 },
    { nome: 'Roupa nobre', preco: 25 },
    { nome: 'Saco de dormir', preco: 1 },
    { nome: 'Saco grande (600 cn)', preco: 2 },
    { nome: 'Saco pequeno (200 cn)', preco: 1 },
    { nome: 'Sino', preco: 1 },
    { nome: 'Tesoura', preco: 1 },
    { nome: 'Tinta (frasqueta) e pena', preco: 5 },
    { nome: 'Tochas (6)', preco: 1 },
    { nome: 'Velas (12)', preco: 1 }
];

module.exports = itens;