const tracos = [
    "Além disso, você possui acne, eczema ou similar.",
    "Além disso, você adora tatuagens ou piercings.",
    "Além disso, você é alcóolatra.",
    "Além disso, você possui alergias e está constantemente com coriza.",
    "Além disso, você ama histórias, literatura ou música.",
    "Além disso, você aprecia carne de humanoides.",
    "Além disso, você é careca e seus cabelos não crescem.",
    "Além disso, você está constantemente mastigando algo, como goma ou fumo.",
    "Além disso, você está constantemente se coçando.",
    "Além disso, você é extremamente cético.",
    "Além disso, você é extremamente religioso.",
    "Além disso, você frequentemente mexe no cabelo.",
    "Além disso, você é fumante.",
    "Além disso, você possui hálito terrível.",
    "Além disso, você tem mania de controle.",
    "Além disso, você tem mania de limpeza e detesta sujeira.",
    "Além disso, você possui uma marca de nascença ou cicatriz.",
    "Além disso, você não gosta de tocar pessoas.",
    "Além disso, você não possui dentes na boca.",
    "Além disso, você não possui um dos dedos da mão.",
    "Além disso, você não sabe nadar.",
    "Além disso, você tem obsessão por boa comida.",
    "Além disso, você tem olhos de cores diferentes.",
    "Além disso, você ostenta exageradamente, usando roupas valiosas, por exemplo.",
    "Além disso, você possui grande superstição.",
    "Além disso, você possui um olho de vidro.",
    "Além disso, você tem problema de visão e usa óculos.",
    "Além disso, você ronca exageradamente.",
    "Além disso, você tem sono profundo.",
    "Além disso, você tem sono leve.",
    "Além disso, você tem sudorese quando sob tensão.",
    "Além disso, você tem algum tique perceptível.",
    "Além disso, você tem gagueira.",
    "Além disso, você tem medo de altura.",
    "Além disso, você tem medo de montar a cavalo.",
    "Além disso, você tem medo de galinhas."
];

module.exports = tracos;